# --- Stage 1: Builder ---
FROM python:3.9-slim as builder

WORKDIR /app

# Встановлюємо компілятори
RUN apt-get update && apt-get install -y --no-install-recommends build-essential

# Створюємо віртуальне середовище
RUN python -m venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"

# Встановлюємо залежності. 
RUN pip install --no-cache-dir torch torchvision pillow requests --index-url https://download.pytorch.org/whl/cpu

# --- Stage 2: Final ---
FROM python:3.9-slim

WORKDIR /app

# Копіюємо віртуальне середовище
COPY --from=builder /opt/venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"

COPY model.pt .
COPY inference.py .

CMD ["python", "inference.py"]