apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql
  namespace: infra-tools
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: postgresql
    targetRevision: 15.5.1
    helm:
      values: |
        image:
          tag: latest 
          pullPolicy: Always
        auth:
          username: mlflow
          password: mlflowpassword
          database: mlflow
        primary:
          persistence:
            enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: infra-tools
  syncPolicy:
    automated:
      prune: true
      selfHeal: true